name: portable_bartender_v2
description: v2 of the portable bartender

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  build_runner: ^2.1.8
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  flex_color_scheme: ^5.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2+1
  freezed: ^1.1.1
  freezed_annotation: ^1.1.0
  google_fonts: ^2.3.1
  hooks_riverpod: ^1.0.3
  json_annotation: ^4.4.0
  json_serializable: ^6.1.5
  riverpod: ^1.0.3

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
