name: portable_bartender_v2
description: v2 of the portable bartender

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^1.0.3
  freezed: ^1.1.1
  freezed_annotation: ^1.1.0
  dio: ^4.0.6
  dartz: ^0.10.1
  build_runner: ^2.1.8
  riverpod: ^1.0.3
  flutter_hooks: ^0.18.2+1
  json_annotation: ^4.4.0
  json_serializable: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true































