// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'drink_entity.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_DrinkEntity _$$_DrinkEntityFromJson(Map<String, dynamic> json) =>
    _$_DrinkEntity(
      id: json['idDrink'] as String?,
      name: json['strDrink'] as String?,
      tags: json['strTags'] as String?,
      category: json['strCategory'] as String?,
      glassType: json['strGlass'] as String?,
      alcoholicType: json['strAlcoholic'] as String?,
      instructions: json['strInstructions'] as String?,
      thumbnailUrl: json['strDrinkThumb'] as String?,
      imageUrl: json['strImageSource'] as String?,
      imageAttribution: json['strImageAttribution'] as String?,
      ingredientOne: json['strIngredient1'] as String?,
      ingredientTwo: json['strIngredient2'] as String?,
      ingredientThree: json['strIngredient3'] as String?,
      ingredientFour: json['strIngredient4'] as String?,
      ingredientFive: json['strIngredient5'] as String?,
      ingredientSix: json['strIngredient6'] as String?,
      ingredientSeven: json['strIngredient7'] as String?,
      ingredientEight: json['strIngredient8'] as String?,
      ingredientNine: json['strIngredient9'] as String?,
      ingredientTen: json['strIngredient10'] as String?,
      ingredientEleven: json['strIngredient11'] as String?,
      ingredientTwelve: json['strIngredient12'] as String?,
      ingredientThirteen: json['strIngredient13'] as String?,
      ingredientFourteen: json['strIngredient14'] as String?,
      ingredientFifteen: json['strIngredient15'] as String?,
      measurementOne: json['strMeasure1'] as String?,
      measurementTwo: json['strMeasure2'] as String?,
      measurementThree: json['strMeasure3'] as String?,
      measurementFour: json['strMeasure4'] as String?,
      measurementFive: json['strMeasure5'] as String?,
      measurementSix: json['strMeasure6'] as String?,
      measurementSeven: json['strMeasure7'] as String?,
      measurementEight: json['strMeasure8'] as String?,
      measurementNine: json['strMeasure9'] as String?,
      measurementTen: json['strMeasure10'] as String?,
      measurementEleven: json['strMeasure11'] as String?,
      measurementTwelve: json['strMeasure12'] as String?,
      measurementThirteen: json['strMeasure13'] as String?,
      measurementFourteen: json['strMeasure14'] as String?,
      measurementFifteen: json['strMeasure15'] as String?,
    );

Map<String, dynamic> _$$_DrinkEntityToJson(_$_DrinkEntity instance) =>
    <String, dynamic>{
      'idDrink': instance.id,
      'strDrink': instance.name,
      'strTags': instance.tags,
      'strCategory': instance.category,
      'strGlass': instance.glassType,
      'strAlcoholic': instance.alcoholicType,
      'strInstructions': instance.instructions,
      'strDrinkThumb': instance.thumbnailUrl,
      'strImageSource': instance.imageUrl,
      'strImageAttribution': instance.imageAttribution,
      'strIngredient1': instance.ingredientOne,
      'strIngredient2': instance.ingredientTwo,
      'strIngredient3': instance.ingredientThree,
      'strIngredient4': instance.ingredientFour,
      'strIngredient5': instance.ingredientFive,
      'strIngredient6': instance.ingredientSix,
      'strIngredient7': instance.ingredientSeven,
      'strIngredient8': instance.ingredientEight,
      'strIngredient9': instance.ingredientNine,
      'strIngredient10': instance.ingredientTen,
      'strIngredient11': instance.ingredientEleven,
      'strIngredient12': instance.ingredientTwelve,
      'strIngredient13': instance.ingredientThirteen,
      'strIngredient14': instance.ingredientFourteen,
      'strIngredient15': instance.ingredientFifteen,
      'strMeasure1': instance.measurementOne,
      'strMeasure2': instance.measurementTwo,
      'strMeasure3': instance.measurementThree,
      'strMeasure4': instance.measurementFour,
      'strMeasure5': instance.measurementFive,
      'strMeasure6': instance.measurementSix,
      'strMeasure7': instance.measurementSeven,
      'strMeasure8': instance.measurementEight,
      'strMeasure9': instance.measurementNine,
      'strMeasure10': instance.measurementTen,
      'strMeasure11': instance.measurementEleven,
      'strMeasure12': instance.measurementTwelve,
      'strMeasure13': instance.measurementThirteen,
      'strMeasure14': instance.measurementFourteen,
      'strMeasure15': instance.measurementFifteen,
    };
